config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :meal
  root to: 'meal#index'
  get '/request_meal', to: 'meal#request_meal' 
end

app/models/concerns/meal.rb
#require_relative '../services/request_meal'

class Meal  
  attr_reader :title, :description, :category, :country, :ingredients, :image, :video

  def initialize(attributes = {})
    @title = attributes[:title]
    @description = attributes[:description]
    @category = attributes[:category]
    @country = attributes[:country]
    @ingredients = attributes[:ingredients]
    @image = attributes[:image]
    @video = attributes[:video]
  end

  def self.create
    meal = RequestMeal.get
    Meal.new(meal)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meal_controller.rb
require_relative '../services/request_meal'
require_relative '../repository/meals_repo'

class MealController < ApplicationController

  def index
  end

  def request_meal
    @meal = Meal.create 
    puts @meal.video
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meal_helper.rb
module MealHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>MealRandomGenerator</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property='og:title' content='Random Meal Generator' />
  <meta property='og:image' content='https://images.unsplash.com/photo-1554998171-89445e31c52b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1410&q=80' />
  <meta property='og:description' content='A simple random meal generator <3' />
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
  <footer class="has-text-centered mb-4">
    <p>Made with <i class="fas fa-heart" style="color: darkred;" aria-hidden="true"></i> by <%= link_to "Paulo Oliveira", "https://github.com/plooliveira", :target => "_blank" %></p>
  </footer>
</body>

</html>

app/views/meal/index.html.erb
<div class=" main columns is-vcentered is-centered mt-6">
  <div class="column is-half has-text-centered">
    <h1 class="title is-1">Feeling hungry?</h1>
    <h2 class="subtitle is-4">Get a delicious random meal</h2>
    <a href=<%= request_meal_path %> class="button is-primary">Get meal <i class="fas fa-utensils ml-2"></i></a>
  </div>
</div>
<div class="meals">
  <p>
    <%= @meal %>
  </p>
</div>

app/views/meal/request_meal.html.erb
<div class="container">
  <div class=" columns is-centered is-mobile">
    <div class=" column is-narrow ">
      <div class="hero mt-6 mb-4">
        <div class="columns">
          <div class="column is-9">
            <h1 class=" title">
              <%= @meal.title%>
            </h1>
            <h2 class="subtitle">
              <%= @meal.country%> food
            </h2>
          </div>
          <div class="column">
            <a data-reflex="click->ExampleReflex#refresh" tyle="width: 158px;" class=" button is-primary">Get a new meal <i class="fas fa-utensils ml-2"></i></a>
          </div>
        </div>
      </div>
      <div class="card meal-img ">
        <div class="card-image">
          <figure class="image is-4by3">
            <img class="" src="<%=@meal.image %>" alt="">
          </figure>
        </div>
      </div>
      <section class="section instructions">
        <div class="columns">

          <div class="column is-two-fifths">
            <section class="section">
              <div class="container">
                <h1 class="title">Igredients</h1>
                <ul class="menu-list">
                  <% @meal.ingredients.each do |ingredient| %>
                  <li>
                    <%= ingredient[:name] %> <span> - <%= ingredient[:measure]%></span>
                  </li>
                  <%end%>
                </ul>
              </div>
            </section>
          </div>

          <div class="coloumn">
            <section class="section">
              <div class="container">
                <h1 class="title">Instructions</h1>
                <p class="meal_desc">
                  <%= @meal.description%>
                </p>
              </div>
            </section>

          </div>
        </div>
      </section>
      <figure class="image is-16by9 mb-6">
        <iframe class="has-ratio" width="640" height="360" src="<%=@meal.video%>" frameborder="0" allowfullscreen></iframe>
      </figure>
    </div>

  </div>
</div>